name: flutter_bumble_clone
description: A Flutter clone of the Bumble app

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.4.2
  cupertino_icons: ^0.1.2
  flutter_platform_widgets: ^0.32.4
  provider: ^4.0.4
  country_code_picker: ^1.3.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_name: ^0.0.1
  flutter_launcher_icons: ^0.7.4

flutter_launcher_name:
  name: "Bumble (Flutter)"

flutter_icons:
  image_path: "assets/icon.jpg"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
